# render.yaml
services:
  - type: web
    name: gemini-chatbot # サービス名
    env: python
    region: oregon # デプロイリージョン
    plan: free # プラン
    branch: main # デプロイするブランチ

    # ビルドコマンド: requirements.txtから依存関係をインストール
    buildCommand: pip install -r requirements.txt

    # 起動コマンド: uvicornでFastAPIアプリケーションを起動
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    # 環境変数 (APIキーを直接コードに記述しているため、ここでは空です)
    # 繰り返しになりますが、環境変数での管理を強く推奨します。
    envVars:
      # - key: GEMINI_API_KEY
      #   value: YOUR_ACTUAL_GEMINI_API_KEY_HERE # ここに記述することも可能ですが非推奨
